{
	"version": 1637922609,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"data/sprite-sheet0.png",
		"data/particles.png",
		"data/sprite2-sheet0.png",
		"data/powerup-sheet0.png",
		"data/particles2.png",
		"data/camera-sheet0.png",
		"data/sprite3-sheet0.png",
		"data/sprite3-sheet1.png",
		"data/sprite3-sheet2.png",
		"data/sprite4-sheet0.png",
		"data/sprite5-sheet0.png",
		"data/vine-boomfull.ogg",
		"data/chord.ogg",
		"data/exp.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}